<a href="https://colab.research.google.com/github/manojmulammagari/data-analysis-python-practice/blob/main/01_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
df=pd.Series([5,4,3,2,1],index=[1,2,3,4,5])
print(df)

1    5
2    4
3    3
4    2
5    1
dtype: int64

In [3]:
import pandas as pd
a=pd.DataFrame({"Name":['Manoj','Priya','Sudeer','vani'],'marks':[96,44,35,19]})
print(a)
a.index

     Name  marks
0   Manoj     96
1   Priya     44
2  Sudeer     35
3    vani     19

RangeIndex(start=0, stop=4, step=1)

In [4]:
a.index

RangeIndex(start=0, stop=4, step=1)

In [5]:
a.shape

(4, 2)

In [6]:
a.size

8

In [7]:
a.columns

Index(['Name', 'marks'], dtype='object')

In [8]:
a.axes

[RangeIndex(start=0, stop=4, step=1), Index(['Name', 'marks'], dtype='object')]

In [9]:
a.dtypes

Name     object
marks     int64
dtype: object

In [10]:
a.values

array([['Manoj', 96],
       ['Priya', 44],
       ['Sudeer', 35],
       ['vani', 19]], dtype=object)

In [11]:
a.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    4 non-null      object
 1   marks   4 non-null      int64
dtypes: int64(1), object(1)
memory usage: 196.0+ bytes

In [12]:
a.describe()

          marks
count   4.00000
mean   48.50000
std    33.31166
min    19.00000
25%    31.00000
50%    39.50000
75%    57.00000
max    96.00000

In [13]:
a.memory_usage()

Index    132
Name      32
marks     32
dtype: int64

In [17]:
a.select_dtypes(include='number')

   marks
0     96
1     44
2     35
3     19

In [18]:
a[['Name','marks']]

     Name  marks
0   Manoj     96
1   Priya     44
2  Sudeer     35
3    vani     19

In [19]:
print(a)

     Name  marks
0   Manoj     96
1   Priya     44
2  Sudeer     35
3    vani     19

In [22]:
a.iloc[0:4,1]

0    96
1    44
2    35
3    19
Name: marks, dtype: int64

In [26]:
a.loc[0:3,['Name','marks']]

     Name  marks
0   Manoj     96
1   Priya     44
2  Sudeer     35
3    vani     19

In [27]:
b=pd.DataFrame({'Language':['Python','JAVA','C++',"HTML"],'Use':['MORE IMPORTANT','NORMAL',"DIfferent","WEB DEVELOP"]})
b

  Language             Use
0   Python  MORE IMPORTANT
1     JAVA          NORMAL
2      C++       DIfferent
3     HTML     WEB DEVELOP

In [28]:
b.shape,b.size,b.ndim

((4, 2), 8, 2)

In [32]:
b.columns

Index(['Language', 'Use'], dtype='object')

In [33]:
b.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Language  4 non-null      object
 1   Use       4 non-null      object
dtypes: object(2)
memory usage: 196.0+ bytes

In [34]:
b.memory_usage()

Index       132
Language     32
Use          32
dtype: int64

In [35]:
b.select_dtypes(include='object')

  Language             Use
0   Python  MORE IMPORTANT
1     JAVA          NORMAL
2      C++       DIfferent
3     HTML     WEB DEVELOP

In [36]:
b['Language']

0    Python
1      JAVA
2       C++
3      HTML
Name: Language, dtype: object

In [37]:
b[['Language','Use']]

  Language             Use
0   Python  MORE IMPORTANT
1     JAVA          NORMAL
2      C++       DIfferent
3     HTML     WEB DEVELOP

In [38]:
b.loc[1:2,'Use']

1       NORMAL
2    DIfferent
Name: Use, dtype: object

In [39]:
b.describe()

       Language             Use
count         4               4
unique        4               4
top      Python  MORE IMPORTANT
freq          1               1