<a href="https://colab.research.google.com/github/manojmulammagari/data-analysis-python-practice/blob/main/Pandas_03.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
df=pd.read_csv('test.csv')
df

,bedroom,bathrooms,area,furnishing,avalable_for,address,floor_number,facing,floor_type,gate_community,...,pooja_room,study_room,others,servant_room,store_room,maintenance_amt,brok_amt,deposit_amt,mnt_amt,rent
0,NaN,2.0,0.0,Semifurnished,All,"Bella Casa Baner, Baner, , Pune, Maharashtra",1,No Direction,Not provided,No,...,0,0,0.0,0.0,0.0,0,0.0,0.0,0.0,18500.0
1,2.0,2.0,1050.0,Semifurnished,All,"Paranjape Blue Ridge, Hinjewadi, , Pune, Mahar...",2,West,Not provided,Yes,...,0,0,0.0,0.0,0.0,0,0.0,63000.0,0.0,21000.0
2,2.0,NaN,900.0,Semifurnished,All,"Simplicity Apartments, Handewadi, , Pune, Maha...",6,No Direction,Not provided,Yes,...,0,0,0.0,0.0,0.0,0,0.0,25000.0,0.0,12000.0
3,3.0,3.0,1100.0,Furnished,Family Only,"GK Dwarka Queens Park, Rahatani, , Pune, Mahar...",1,East,Others,Yes,...,0,0,0.0,0.0,0.0,0,24000.0,3.0,0.0,24000.0
4,1.0,1.0,605.0,Semifurnished,Family Only,"Anandtara Sayajiraje Avenue, Sasane Colony, , ...",4,East,Vitrified,Yes,...,0,0,1.0,0.0,0.0,0,0.0,3.0,0.0,13500.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5356,2.0,2.0,0.0,Unfurnished,All,"Kesar Imperial Blue, Dighi, , Pune, Maharashtra",2,East,Marble,Yes,...,0,0,0.0,0.0,0.0,0,0.0,30000.0,0.0,14000.0
5357,1.0,1.0,0.0,Unfurnished,Bachelors (Men Only),"Karve Nagar, , Pune, Maharashtra",0,No Direction,Not provided,No,...,0,0,0.0,0.0,0.0,0,0.0,20000.0,0.0,10000.0
5358,3.0,3.0,1300.0,Semifurnished,All,"Kolte Patil IVY Estate, Wagholi, , Pune, Mahar...",5,North-West,Marble,Yes,...,0,0,0.0,0.0,1.0,0,16700.0,45000.0,0.0,16700.0
5359,3.0,3.0,1450.0,Unfurnished,All,"Pride Aloma County, Aundh, , Pune, Maharashtra",9,South-East,Vitrified,Yes,...,0,0,1.0,0.0,0.0,Maintenance 1/ (/ month,1.0,100000.0,1.0,33000.0
5360,2.0,2.0,850.0,Furnished,All,"Swapan Lok Society, Koregaon park, , Pune, Mah...",4,North,Granite,Yes,...,0,0,1.0,0.0,0.0,0,40000.0,120000.0,0.0,40000.0

In [3]:
df[df['facing']=='East']

,bedroom,bathrooms,area,furnishing,avalable_for,address,floor_number,facing,floor_type,gate_community,...,pooja_room,study_room,others,servant_room,store_room,maintenance_amt,brok_amt,deposit_amt,mnt_amt,rent
3,3.0,3.0,1100.0,Furnished,Family Only,"GK Dwarka Queens Park, Rahatani, , Pune, Mahar...",1,East,Others,Yes,...,0,0,0.0,0.0,0.0,0,24000.0,3.0,0.0,24000.0
4,1.0,1.0,605.0,Semifurnished,Family Only,"Anandtara Sayajiraje Avenue, Sasane Colony, , ...",4,East,Vitrified,Yes,...,0,0,1.0,0.0,0.0,0,0.0,3.0,0.0,13500.0
10,2.0,2.0,1055.0,Semifurnished,"Family , Bachelors (Women Only)","Magarpatta Cosmos Apartment, Hadapsar, , Pune,...",9,East,Vitrified,Yes,...,0,0,0.0,0.0,0.0,0,0.0,50000.0,0.0,19000.0
11,1.0,2.0,780.0,Semifurnished,All,"SKYi First, Bhugaon, , Pune, Maharashtra",3,East,Others,Yes,...,1,1,1.0,1.0,0.0,0,0.0,0.0,0.0,8000.0
18,3.0,3.0,1250.0,Unfurnished,All,"Nyati Elysia, Kharadi, , Pune, Maharashtra",2,East,Others,Yes,...,0,0,1.0,0.0,0.0,0,28000.0,3.0,0.0,28000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5350,1.0,1.0,320.0,Semifurnished,All,"Sacha Sauda Gurudatta Housing Society, Dhankaw...",0,East,Not provided,No,...,0,0,0.0,0.0,0.0,0,0.0,6000.0,0.0,6000.0
5352,3.0,3.0,1200.0,Furnished,Family Only,"Avinash, kothrud, , Pune, Maharashtra",5,East,Vitrified,Yes,...,0,1,0.0,0.0,0.0,0,90000.0,200000.0,0.0,45000.0
5353,2.0,2.0,1000.0,Semifurnished,All,"Regalia appartment , Eon Free Zone , , Pune, M...",2,East,Not provided,Yes,...,0,0,0.0,0.0,0.0,0,0.0,0.0,0.0,16000.0
5355,2.0,2.0,1028.0,Unfurnished,All,"Gera South, Eon Free Zone , , Pune, Maharashtra",4,East,Marble,Yes,...,0,0,0.0,0.0,0.0,0,25000.0,80000.0,0.0,25000.0
5356,2.0,2.0,0.0,Unfurnished,All,"Kesar Imperial Blue, Dighi, , Pune, Maharashtra",2,East,Marble,Yes,...,0,0,0.0,0.0,0.0,0,0.0,30000.0,0.0,14000.0

In [7]:
df[df['rent']==df['rent'].min()]

,bedroom,bathrooms,area,furnishing,avalable_for,address,floor_number,facing,floor_type,gate_community,...,pooja_room,study_room,others,servant_room,store_room,maintenance_amt,brok_amt,deposit_amt,mnt_amt,rent
1119,1.0,1.0,550.0,Semifurnished,All,"Premanand CHS, Rajendra Nagar, , Pune, Maharas...",2,No Direction,Not provided,No,...,0,0,0.0,0.0,0.0,0,0.0,0.0,0.0,1600.0

In [18]:
df[df['rent']==df['rent'].max()]

,bedroom,bathrooms,area,furnishing,avalable_for,address,floor_number,facing,floor_type,gate_community,...,pooja_room,study_room,others,servant_room,store_room,maintenance_amt,brok_amt,deposit_amt,mnt_amt,rent
3412,4.0,4.0,2200.0,Unfurnished,Family Only,"Vascon Willows, Baner, , Pune, Maharashtra",8,No Direction,Vitrified,No,...,0,0,0.0,0.0,0.0,0,95000.0,500000.0,0.0,95000.0

In [21]:
df[df['floor_number']>8]

,bedroom,bathrooms,area,furnishing,avalable_for,address,floor_number,facing,floor_type,gate_community,...,pooja_room,study_room,others,servant_room,store_room,maintenance_amt,brok_amt,deposit_amt,mnt_amt,rent
8,1.0,1.0,0.0,Furnished,Family Only,"Ram India livogue, Malwadi, , Pune, Maharashtra",9,No Direction,Not provided,Yes,...,0,0,0.0,0.0,0.0,0,0.0,3.0,0.0,20000.0
10,2.0,2.0,1055.0,Semifurnished,"Family , Bachelors (Women Only)","Magarpatta Cosmos Apartment, Hadapsar, , Pune,...",9,East,Vitrified,Yes,...,0,0,0.0,0.0,0.0,0,0.0,50000.0,0.0,19000.0
38,2.0,2.0,888.0,Unfurnished,All,"Kalpataru Harmony, Kaspate Vasti, , Pune, Maha...",9,East,Vitrified,Yes,...,0,0,0.0,0.0,0.0,0,20000.0,50000.0,0.0,20000.0
41,3.0,3.0,1350.0,Unfurnished,All,"Bramha Avenue, NIBM, , Pune, Maharashtra",9,East,Vitrified,Yes,...,0,0,0.0,0.0,1.0,Maintenance 2800/ (/ month,45000.0,3.0,2800.0,27000.0
93,2.0,2.0,850.0,Unfurnished,"Family , Bachelors (Women Only)","Ravinanda Skylights, Wagholi, , Pune, Maharashtra",9,East,Marble,No,...,0,0,0.0,0.0,0.0,0,0.0,30000.0,0.0,12000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5199,2.0,2.0,0.0,Unfurnished,Family Only,"Green Groves Calandula, Wagholi, , Pune, Mahar...",9,No Direction,Not provided,No,...,0,0,0.0,0.0,0.0,0,0.0,50000.0,0.0,15000.0
5242,3.0,3.0,0.0,Furnished,All,"Kalpataru Serenity, Manjri, , Pune, Maharashtra",9,No Direction,Not provided,Yes,...,0,0,0.0,0.0,0.0,0,0.0,150000.0,0.0,35000.0
5305,2.0,2.0,900.0,Semifurnished,All,"Omega Mantri Eternity Plus, Kundan Nagar, , Pu...",9,No Direction,Not provided,No,...,0,0,0.0,0.0,0.0,0,0.0,60000.0,0.0,20500.0
5324,2.0,2.0,840.0,Unfurnished,All,"Kolte Patil Downtown Langston, Ashoka Nagar, ,...",9,South-East,Vitrified,Yes,...,0,0,0.0,0.0,0.0,0,0.0,3.0,0.0,23500.0
5359,3.0,3.0,1450.0,Unfurnished,All,"Pride Aloma County, Aundh, , Pune, Maharashtra",9,South-East,Vitrified,Yes,...,0,0,1.0,0.0,0.0,Maintenance 1/ (/ month,1.0,100000.0,1.0,33000.0

In [22]:
df[(df['facing']=='East')&(df['rent']<8000)]

,bedroom,bathrooms,area,furnishing,avalable_for,address,floor_number,facing,floor_type,gate_community,...,pooja_room,study_room,others,servant_room,store_room,maintenance_amt,brok_amt,deposit_amt,mnt_amt,rent
106,1.0,1.0,0.0,Unfurnished,Family Only,"Achal Farm Society, Ambegaon Kh, , Pune, Mahar...",1,East,Ceramic,Yes,...,0,0,0.0,0.0,0.0,0,0.0,15000.0,0.0,5500.0
111,2.0,1.0,0.0,Semifurnished,All,"Aayush Park II Society Talegaon Dabhade, Taleg...",5,East,Marble,Yes,...,0,0,0.0,0.0,0.0,0,0.0,20000.0,0.0,7500.0
208,1.0,1.0,600.0,Unfurnished,All,"ashthavinayak housing society , shelar mala, ,...",0,East,Not provided,No,...,0,0,0.0,0.0,0.0,0,0.0,12000.0,0.0,7000.0
349,1.0,1.0,0.0,Unfurnished,All,"Lane No 2, Pawar Nagar, , Pune, Maharashtra",1,East,Vitrified,No,...,0,0,0.0,0.0,0.0,0,0.0,15000.0,0.0,6000.0
356,1.0,1.0,570.0,Unfurnished,All,"Laxminarayan Apartment, Balaji Nagar, , Pune, ...",0,East,Vitrified,No,...,0,0,0.0,0.0,0.0,0,0.0,20000.0,0.0,7500.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5105,2.0,2.0,418.0,Unfurnished,All,"Xrbia Hinjewadi, Hinjewadi, , Pune, Maharashtra",7,East,Marble,Yes,...,1,1,0.0,1.0,1.0,0,3500.0,15000.0,0.0,7050.0
5220,1.0,1.0,550.0,Unfurnished,Family Only,"Oxygen Valley, Narhe, , Pune, Maharashtra",1,East,Vitrified,Yes,...,0,0,0.0,0.0,0.0,0,0.0,4.0,0.0,7000.0
5307,1.0,1.0,480.0,Semifurnished,Family Only,"Sai Shraddha, Ambegaon Bk, , Pune, Maharashtra",6,East,Vitrified,Yes,...,0,0,0.0,0.0,0.0,Maintenance 1200/ (/ month,0.0,20000.0,1200.0,7200.0
5345,1.0,1.0,0.0,Unfurnished,Family Only,"122, Vrindavan Apartment, Kadolkar Colony, Tal...",0,East,Granite,Yes,...,0,0,0.0,0.0,0.0,0,0.0,20000.0,0.0,6500.0
5350,1.0,1.0,320.0,Semifurnished,All,"Sacha Sauda Gurudatta Housing Society, Dhankaw...",0,East,Not provided,No,...,0,0,0.0,0.0,0.0,0,0.0,6000.0,0.0,6000.0

In [23]:
df[(df['facing']=='East')|(df['rent']<80000)|(df['floor_number']>7)]

,bedroom,bathrooms,area,furnishing,avalable_for,address,floor_number,facing,floor_type,gate_community,...,pooja_room,study_room,others,servant_room,store_room,maintenance_amt,brok_amt,deposit_amt,mnt_amt,rent
0,NaN,2.0,0.0,Semifurnished,All,"Bella Casa Baner, Baner, , Pune, Maharashtra",1,No Direction,Not provided,No,...,0,0,0.0,0.0,0.0,0,0.0,0.0,0.0,18500.0
1,2.0,2.0,1050.0,Semifurnished,All,"Paranjape Blue Ridge, Hinjewadi, , Pune, Mahar...",2,West,Not provided,Yes,...,0,0,0.0,0.0,0.0,0,0.0,63000.0,0.0,21000.0
2,2.0,NaN,900.0,Semifurnished,All,"Simplicity Apartments, Handewadi, , Pune, Maha...",6,No Direction,Not provided,Yes,...,0,0,0.0,0.0,0.0,0,0.0,25000.0,0.0,12000.0
3,3.0,3.0,1100.0,Furnished,Family Only,"GK Dwarka Queens Park, Rahatani, , Pune, Mahar...",1,East,Others,Yes,...,0,0,0.0,0.0,0.0,0,24000.0,3.0,0.0,24000.0
4,1.0,1.0,605.0,Semifurnished,Family Only,"Anandtara Sayajiraje Avenue, Sasane Colony, , ...",4,East,Vitrified,Yes,...,0,0,1.0,0.0,0.0,0,0.0,3.0,0.0,13500.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5356,2.0,2.0,0.0,Unfurnished,All,"Kesar Imperial Blue, Dighi, , Pune, Maharashtra",2,East,Marble,Yes,...,0,0,0.0,0.0,0.0,0,0.0,30000.0,0.0,14000.0
5357,1.0,1.0,0.0,Unfurnished,Bachelors (Men Only),"Karve Nagar, , Pune, Maharashtra",0,No Direction,Not provided,No,...,0,0,0.0,0.0,0.0,0,0.0,20000.0,0.0,10000.0
5358,3.0,3.0,1300.0,Semifurnished,All,"Kolte Patil IVY Estate, Wagholi, , Pune, Mahar...",5,North-West,Marble,Yes,...,0,0,0.0,0.0,1.0,0,16700.0,45000.0,0.0,16700.0
5359,3.0,3.0,1450.0,Unfurnished,All,"Pride Aloma County, Aundh, , Pune, Maharashtra",9,South-East,Vitrified,Yes,...,0,0,1.0,0.0,0.0,Maintenance 1/ (/ month,1.0,100000.0,1.0,33000.0
5360,2.0,2.0,850.0,Furnished,All,"Swapan Lok Society, Koregaon park, , Pune, Mah...",4,North,Granite,Yes,...,0,0,1.0,0.0,0.0,0,40000.0,120000.0,0.0,40000.0

In [31]:
c=df[(df['address'].str.contains('Pune'))&(df['rent']>80000)]
c.reset_index(drop=True)

,bedroom,bathrooms,area,furnishing,avalable_for,address,floor_number,facing,floor_type,gate_community,...,pooja_room,study_room,others,servant_room,store_room,maintenance_amt,brok_amt,deposit_amt,mnt_amt,rent
0,4.0,4.0,0.0,Furnished,Bachelors (Men/Women),"Darode Jog Blossom Bouleward, Koregaon Park, ,...",4,No Direction,Marble,Yes,...,0,0,1.0,0.0,0.0,0,85000.0,550000.0,0.0,85000.0
1,3.0,2.0,1400.0,Furnished,All,"Princeton Flair Co Operative Housing Society, ...",1,No Direction,Marble,Yes,...,0,1,0.0,0.0,0.0,0,0.0,3.0,0.0,85000.0
2,4.0,4.0,0.0,Furnished,Family Only,"Vascon Willows, Baner, , Pune, Maharashtra",5,No Direction,Not provided,Yes,...,0,0,0.0,0.0,0.0,0,0.0,5.0,0.0,90000.0
3,4.0,4.0,2050.0,Furnished,Family Only,"Vascon Paradise, Baner, , Pune, Maharashtra",5,East,Vitrified,Yes,...,1,0,0.0,0.0,0.0,Maintenance 2000/ (/ month,85000.0,255000.0,2000.0,85000.0
4,4.0,5.0,0.0,Semifurnished,Family Only,"Panchshil One North, Hadapsar, , Pune, Maharas...",5,East,Vitrified,Yes,...,0,1,1.0,1.0,0.0,0,90000.0,300000.0,0.0,90000.0
5,3.0,4.0,0.0,Semifurnished,Family Only,"Aundh Gaon, , Pune, Maharashtra",0,No Direction,Not provided,No,...,0,0,0.0,0.0,0.0,0,0.0,300000.0,0.0,90000.0
6,4.0,5.0,0.0,Semifurnished,Family Only,"Panchshil One North, Hadapsar, , Pune, Maharas...",4,East,Marble,No,...,0,0,0.0,1.0,0.0,0,85000.0,4.0,0.0,85000.0
7,4.0,4.0,0.0,Semifurnished,All,"Samar Paradise, Aundh, Pune, Kubera Gulashan, ...",0,East,Marble,No,...,1,1,0.0,1.0,1.0,0,0.0,4.0,0.0,90000.0
8,4.0,4.0,2200.0,Unfurnished,Family Only,"Vascon Willows, Baner, , Pune, Maharashtra",8,No Direction,Vitrified,No,...,0,0,0.0,0.0,0.0,0,95000.0,500000.0,0.0,95000.0
9,4.0,4.0,15437.0,Semifurnished,All,"Park Grandeur, Baner, , Pune, Maharashtra",9,North-East,Vitrified,No,...,0,0,0.0,1.0,0.0,0,250000.0,850000.0,0.0,85000.0
10,4.0,4.0,0.0,Furnished,Family Only,"GPC Project, Sahawas Society Lane No -2, , Pun...",0,No Direction,Not provided,Yes,...,0,0,0.0,0.0,0.0,0,100000.0,500000.0,0.0,90000.0

In [32]:
df[df['area']==1400].reset_index(drop=True)

,bedroom,bathrooms,area,furnishing,avalable_for,address,floor_number,facing,floor_type,gate_community,...,pooja_room,study_room,others,servant_room,store_room,maintenance_amt,brok_amt,deposit_amt,mnt_amt,rent
0,3.0,3.0,1400.0,Unfurnished,All,"Goel Ganga Satellite, Wanowrie, , Pune, Mahara...",9,East,Vitrified,Yes,...,0,0,0.0,0.0,1.0,Maintenance 2500/ (/ month,45000.0,3.0,2500.0,27000.0
1,3.0,3.0,1400.0,Unfurnished,All,"Sudhir Mandke Advantage Homes, Lullanagar, , P...",1,East,Vitrified,Yes,...,0,0,0.0,0.0,1.0,Maintenance 2500/ (/ month,50000.0,3.0,2500.0,26000.0
2,3.0,2.0,1400.0,Furnished,All,"Princeton Flair Co Operative Housing Society, ...",1,No Direction,Marble,Yes,...,0,1,0.0,0.0,0.0,0,0.0,3.0,0.0,85000.0
3,3.0,3.0,1400.0,Unfurnished,All,"Venkatesh Flora, Mundhwa, , Pune, Maharashtra",4,East,Spartex,Yes,...,0,0,0.0,0.0,0.0,0,0.0,5.0,0.0,30000.0
4,3.0,3.0,1400.0,Furnished,Family Only,"Amit 9 Green Park, Sahakar Nagar II, , Pune, M...",4,East,Ceramic,Yes,...,0,0,0.0,0.0,0.0,Maintenance 4400/ (/ month,0.0,200000.0,4400.0,36000.0
5,3.0,3.0,1400.0,Unfurnished,All,"Bramha Exuberance, NIBM, , Pune, Maharashtra",5,East,Vitrified,Yes,...,0,0,0.0,0.0,1.0,Maintenance 2500/ (/ month,45000.0,3.0,2500.0,26000.0
6,3.0,3.0,1400.0,Semifurnished,All,"Paranjape Blue Ridge, Hinjewadi, , Pune, Mahar...",1,East,Vitrified,Yes,...,0,0,1.0,0.0,0.0,0,31000.0,93000.0,0.0,25000.0
7,3.0,3.0,1400.0,Unfurnished,Family Only,"Tuscan Estate Signature Meadows, Kharadi, , Pu...",1,South-West,Marble,Yes,...,1,1,0.0,0.0,0.0,0,31000.0,3.0,0.0,31000.0
8,3.0,3.0,1400.0,Furnished,Family Only,"Marvel Brisa, Balewadi, , Pune, Maharashtra",7,East,Vitrified,No,...,0,0,1.0,0.0,0.0,0,50000.0,200000.0,0.0,50000.0
9,3.0,3.0,1400.0,Unfurnished,All,"Brahma Estate, Kondhwa, , Pune, Maharashtra",2,East,Vitrified,Yes,...,0,0,0.0,0.0,1.0,Maintenance 2500/ (/ month,33000.0,3.0,2500.0,23000.0
10,3.0,3.0,1400.0,Unfurnished,"Family , Bachelors (Men Only)","Decent Residency, On Nagar Road Opposite Viman...",2,No Direction,Vitrified,No,...,0,0,0.0,0.0,0.0,0,0.0,3.0,0.0,25000.0
11,3.0,3.0,1400.0,Unfurnished,Family Only,"Kalaapi Sucasa, Shankar Kalat Nagar, , Pune, M...",6,East,Vitrified,Yes,...,0,0,0.0,0.0,0.0,0,20000.0,60000.0,0.0,20000.0
12,3.0,3.0,1400.0,Unfurnished,All,"Kailash Manas Apartments, NIBM, , Pune, Mahara...",5,East,Vitrified,Yes,...,0,0,1.0,0.0,1.0,Maintenance 2000/ (/ month,36000.0,85000.0,2000.0,18000.0
13,3.0,3.0,1400.0,Furnished,All,"Bhosale Garden, Hadapsar, , Pune, Maharashtra",1,North-East,Spartex,Yes,...,0,0,0.0,0.0,0.0,0,0.0,60000.0,0.0,24000.0
14,3.0,3.0,1400.0,Semifurnished,Family Only,"Good society, Aundh, , Pune, Maharashtra",1,East,Vitrified,Yes,...,0,0,0.0,0.0,0.0,0,28000.0,85000.0,0.0,28000.0
15,3.0,3.0,1400.0,Semifurnished,All,"Wadhwani Ganeesham PH 2, Pimple Saudagar, , Pu...",1,North-East,Wood,Yes,...,0,0,0.0,0.0,0.0,Maintenance 3/ (/ month,0.0,3.0,3.0,24000.0
16,3.0,3.0,1400.0,Unfurnished,All,"Beverly Hills Residences, Lullanagar, , Pune, ...",3,East,Vitrified,Yes,...,0,0,0.0,0.0,1.0,Maintenance 1200/ (/ month,45000.0,3.0,1200.0,33000.0
17,3.0,3.0,1400.0,Unfurnished,All,"Brahma Estate, Kondhwa, , Pune, Maharashtra",7,East,Vitrified,Yes,...,0,0,0.0,0.0,1.0,Maintenance 2500/ (/ month,33000.0,3.0,2500.0,25000.0
18,3.0,3.0,1400.0,Unfurnished,All,"Raheja Vista Phase 3, NIBM, , Pune, Maharashtra",5,East,Vitrified,Yes,...,0,0,0.0,0.0,1.0,Maintenance 1500/ (/ month,3.0,3.0,1500.0,23000.0
19,2.0,1.0,1400.0,Semifurnished,Family Only,"Gharkul Soceity, Vadagaonsheri, , Pune, Mahara...",1,No Direction,Not provided,No,...,0,0,0.0,0.0,0.0,0,0.0,50000.0,0.0,20000.0
20,3.0,3.0,1400.0,Semifurnished,All,"Casa Grande, Koregaon Park, , Pune, Maharashtra",4,North,Vitrified,Yes,...,0,0,0.0,0.0,0.0,0,40000.0,160000.0,0.0,40000.0
21,2.0,2.0,1400.0,Unfurnished,All,"Clover Highlands, Kondhwa, , Pune, Maharashtra",1,East,Vitrified,Yes,...,0,0,1.0,0.0,1.0,Maintenance 2375/ (/ month,33000.0,3.0,2375.0,24000.0
22,3.0,2.0,1400.0,Semifurnished,All,"Rachana Garden Estate, Aundh, , Pune, Maharashtra",4,No Direction,Not provided,No,...,1,1,1.0,0.0,0.0,0,0.0,0.0,0.0,30000.0
23,3.0,3.0,1400.0,Semifurnished,Family Only,"Marvel Enigma, Kharadi, , Pune, Maharashtra",5,North-West,Vitrified,Yes,...,0,0,0.0,0.0,1.0,0,30.0,100000.0,0.0,38000.0

In [33]:
d=pd.read_excel('/content/df.xlsx')
d

,bedroom,bathrooms,area,furnishing,avalable_for,address,floor_number,facing,floor_type,gate_community,...,pooja_room,study_room,others,servant_room,store_room,maintenance_amt,brok_amt,deposit_amt,mnt_amt,rent
0,NaN,2.0,0.0,Semifurnished,All,"Bella Casa Baner, Baner, , Pune, Maharashtra",1,No Direction,Not provided,No,...,0,0,0.0,0.0,0.0,0,0.0,0.0,0.0,18500.0
1,2.0,2.0,1050.0,Semifurnished,All,"Paranjape Blue Ridge, Hinjewadi, , Pune, Mahar...",2,West,Not provided,Yes,...,0,0,0.0,0.0,0.0,0,0.0,63000.0,0.0,21000.0
2,2.0,NaN,900.0,Semifurnished,All,"Simplicity Apartments, Handewadi, , Pune, Maha...",6,No Direction,Not provided,Yes,...,0,0,0.0,0.0,0.0,0,0.0,25000.0,0.0,12000.0
3,3.0,3.0,1100.0,Furnished,Family Only,"GK Dwarka Queens Park, Rahatani, , Pune, Mahar...",1,East,Others,Yes,...,0,0,0.0,0.0,0.0,0,24000.0,3.0,0.0,24000.0
4,1.0,1.0,605.0,Semifurnished,Family Only,"Anandtara Sayajiraje Avenue, Sasane Colony, , ...",4,East,Vitrified,Yes,...,0,0,1.0,0.0,0.0,0,0.0,3.0,0.0,13500.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5356,2.0,2.0,0.0,Unfurnished,All,"Kesar Imperial Blue, Dighi, , Pune, Maharashtra",2,East,Marble,Yes,...,0,0,0.0,0.0,0.0,0,0.0,30000.0,0.0,14000.0
5357,1.0,1.0,0.0,Unfurnished,Bachelors (Men Only),"Karve Nagar, , Pune, Maharashtra",0,No Direction,Not provided,No,...,0,0,0.0,0.0,0.0,0,0.0,20000.0,0.0,10000.0
5358,3.0,3.0,1300.0,Semifurnished,All,"Kolte Patil IVY Estate, Wagholi, , Pune, Mahar...",5,North-West,Marble,Yes,...,0,0,0.0,0.0,1.0,0,16700.0,45000.0,0.0,16700.0
5359,3.0,3.0,1450.0,Unfurnished,All,"Pride Aloma County, Aundh, , Pune, Maharashtra",9,South-East,Vitrified,Yes,...,0,0,1.0,0.0,0.0,Maintenance 1/ (/ month,1.0,100000.0,1.0,33000.0
5360,2.0,2.0,850.0,Furnished,All,"Swapan Lok Society, Koregaon park, , Pune, Mah...",4,North,Granite,Yes,...,0,0,1.0,0.0,0.0,0,40000.0,120000.0,0.0,40000.0

In [35]:
d.isnull()

,bedroom,bathrooms,area,furnishing,avalable_for,address,floor_number,facing,floor_type,gate_community,...,pooja_room,study_room,others,servant_room,store_room,maintenance_amt,brok_amt,deposit_amt,mnt_amt,rent
0,True,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,True,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5356,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
5357,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
5358,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
5359,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
5360,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [ ]:
d.isnull().sum()

bedroom                 1
bathrooms               1
area                    0
furnishing              0
avalable_for           18
address                 0
floor_number            0
facing                  0
floor_type              0
gate_community          0
corner_pro              1
parking                 1
wheelchairadption    4399
petfacility          4160
aggDur                  3
noticeDur               0
lightbill               4
powerbackup             0
propertyage             0
no_room                 2
pooja_room              0
study_room              0
others                  1
servant_room            1
store_room              2
maintenance_amt         1
brok_amt                1
deposit_amt             2
mnt_amt                 0
rent                    0
dtype: int64

In [36]:
d.isnull().sum().sum()

np.int64(8598)

In [37]:
d.isnull().sum()/len(d)*100

bedroom               0.018653
bathrooms             0.018653
area                  0.000000
furnishing            0.000000
avalable_for          0.335758
address               0.000000
floor_number          0.000000
facing                0.000000
floor_type            0.000000
gate_community        0.000000
corner_pro            0.018653
parking               0.018653
wheelchairadption    82.055587
petfacility          77.597463
aggDur                0.055960
noticeDur             0.000000
lightbill             0.074613
powerbackup           0.000000
propertyage           0.000000
no_room               0.037306
pooja_room            0.000000
study_room            0.000000
others                0.018653
servant_room          0.018653
store_room            0.037306
maintenance_amt       0.018653
brok_amt              0.018653
deposit_amt           0.037306
mnt_amt               0.000000
rent                  0.000000
dtype: float64

In [38]:
d.dropna()

,bedroom,bathrooms,area,furnishing,avalable_for,address,floor_number,facing,floor_type,gate_community,...,pooja_room,study_room,others,servant_room,store_room,maintenance_amt,brok_amt,deposit_amt,mnt_amt,rent
1,2.0,2.0,1050.0,Semifurnished,All,"Paranjape Blue Ridge, Hinjewadi, , Pune, Mahar...",2,West,Not provided,Yes,...,0,0,0.0,0.0,0.0,0,0.0,63000.0,0.0,21000.0
3,3.0,3.0,1100.0,Furnished,Family Only,"GK Dwarka Queens Park, Rahatani, , Pune, Mahar...",1,East,Others,Yes,...,0,0,0.0,0.0,0.0,0,24000.0,3.0,0.0,24000.0
4,1.0,1.0,605.0,Semifurnished,Family Only,"Anandtara Sayajiraje Avenue, Sasane Colony, , ...",4,East,Vitrified,Yes,...,0,0,1.0,0.0,0.0,0,0.0,3.0,0.0,13500.0
11,1.0,2.0,780.0,Semifurnished,All,"SKYi First, Bhugaon, , Pune, Maharashtra",3,East,Others,Yes,...,1,1,1.0,1.0,0.0,0,0.0,0.0,0.0,8000.0
22,2.0,2.0,0.0,Furnished,"Family , Bachelors (Women Only)","Nyati Serenity Enclave, Mohamadwadi, , Pune, M...",0,No Direction,Not provided,Yes,...,0,0,0.0,0.0,0.0,0,27000.0,60000.0,0.0,27000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5343,3.0,3.0,1500.0,Unfurnished,All,"Clover Highlands, Kondhwa, , Pune, Maharashtra",2,East,Vitrified,Yes,...,0,0,0.0,0.0,1.0,Maintenance 1500/ (/ month,37000.0,3.0,1500.0,31500.0
5348,2.0,2.0,800.0,Unfurnished,"Family , Bachelors (Women Only)","Guardian Eastern Meadows, Kharadi, , Pune, Mah...",4,No Direction,Vitrified,Yes,...,0,0,1.0,0.0,0.0,0,0.0,6.0,0.0,21000.0
5349,2.0,2.0,1240.0,Furnished,All,"Amanora Neo Towers, Hadapsar, , Pune, Maharashtra",1,No Direction,Not provided,Yes,...,0,0,0.0,0.0,0.0,0,0.0,2.0,0.0,35000.0
5355,2.0,2.0,1028.0,Unfurnished,All,"Gera South, Eon Free Zone , , Pune, Maharashtra",4,East,Marble,Yes,...,0,0,0.0,0.0,0.0,0,25000.0,80000.0,0.0,25000.0
5360,2.0,2.0,850.0,Furnished,All,"Swapan Lok Society, Koregaon park, , Pune, Mah...",4,North,Granite,Yes,...,0,0,1.0,0.0,0.0,0,40000.0,120000.0,0.0,40000.0

In [39]:
d.dropna(axis=1)

,area,furnishing,address,floor_number,facing,floor_type,gate_community,noticeDur,powerbackup,propertyage,pooja_room,study_room,mnt_amt,rent
0,0.0,Semifurnished,"Bella Casa Baner, Baner, , Pune, Maharashtra",1,No Direction,Not provided,No,0,0,1 to 5 Year Old,0,0,0.0,18500.0
1,1050.0,Semifurnished,"Paranjape Blue Ridge, Hinjewadi, , Pune, Mahar...",2,West,Not provided,Yes,1,1,0 to 1 Year Old,0,0,0.0,21000.0
2,900.0,Semifurnished,"Simplicity Apartments, Handewadi, , Pune, Maha...",6,No Direction,Not provided,Yes,1,2,5 to 10 Year Old,0,0,0.0,12000.0
3,1100.0,Furnished,"GK Dwarka Queens Park, Rahatani, , Pune, Mahar...",1,East,Others,Yes,1,1,5 to 10 Year Old,0,0,0.0,24000.0
4,605.0,Semifurnished,"Anandtara Sayajiraje Avenue, Sasane Colony, , ...",4,East,Vitrified,Yes,1,1,5 to 10 Year Old,0,0,0.0,13500.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5356,0.0,Unfurnished,"Kesar Imperial Blue, Dighi, , Pune, Maharashtra",2,East,Marble,Yes,1,0,0 to 1 Year Old,0,0,0.0,14000.0
5357,0.0,Unfurnished,"Karve Nagar, , Pune, Maharashtra",0,No Direction,Not provided,No,0,0,5 to 10 Year Old,0,0,0.0,10000.0
5358,1300.0,Semifurnished,"Kolte Patil IVY Estate, Wagholi, , Pune, Mahar...",5,North-West,Marble,Yes,1,2,0 to 1 Year Old,0,0,0.0,16700.0
5359,1450.0,Unfurnished,"Pride Aloma County, Aundh, , Pune, Maharashtra",9,South-East,Vitrified,Yes,1,2,5 to 10 Year Old,0,0,1.0,33000.0
5360,850.0,Furnished,"Swapan Lok Society, Koregaon park, , Pune, Mah...",4,North,Granite,Yes,1,2,10+ Year Old,0,0,0.0,40000.0

In [40]:
d.dropna(subset=['bedroom'])

,bedroom,bathrooms,area,furnishing,avalable_for,address,floor_number,facing,floor_type,gate_community,...,pooja_room,study_room,others,servant_room,store_room,maintenance_amt,brok_amt,deposit_amt,mnt_amt,rent
1,2.0,2.0,1050.0,Semifurnished,All,"Paranjape Blue Ridge, Hinjewadi, , Pune, Mahar...",2,West,Not provided,Yes,...,0,0,0.0,0.0,0.0,0,0.0,63000.0,0.0,21000.0
2,2.0,NaN,900.0,Semifurnished,All,"Simplicity Apartments, Handewadi, , Pune, Maha...",6,No Direction,Not provided,Yes,...,0,0,0.0,0.0,0.0,0,0.0,25000.0,0.0,12000.0
3,3.0,3.0,1100.0,Furnished,Family Only,"GK Dwarka Queens Park, Rahatani, , Pune, Mahar...",1,East,Others,Yes,...,0,0,0.0,0.0,0.0,0,24000.0,3.0,0.0,24000.0
4,1.0,1.0,605.0,Semifurnished,Family Only,"Anandtara Sayajiraje Avenue, Sasane Colony, , ...",4,East,Vitrified,Yes,...,0,0,1.0,0.0,0.0,0,0.0,3.0,0.0,13500.0
5,1.0,1.0,0.0,Unfurnished,All,"New Sanghvi, , Pune, Maharashtra",1,No Direction,Not provided,No,...,0,0,0.0,0.0,0.0,0,0.0,20000.0,0.0,10000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5356,2.0,2.0,0.0,Unfurnished,All,"Kesar Imperial Blue, Dighi, , Pune, Maharashtra",2,East,Marble,Yes,...,0,0,0.0,0.0,0.0,0,0.0,30000.0,0.0,14000.0
5357,1.0,1.0,0.0,Unfurnished,Bachelors (Men Only),"Karve Nagar, , Pune, Maharashtra",0,No Direction,Not provided,No,...,0,0,0.0,0.0,0.0,0,0.0,20000.0,0.0,10000.0
5358,3.0,3.0,1300.0,Semifurnished,All,"Kolte Patil IVY Estate, Wagholi, , Pune, Mahar...",5,North-West,Marble,Yes,...,0,0,0.0,0.0,1.0,0,16700.0,45000.0,0.0,16700.0
5359,3.0,3.0,1450.0,Unfurnished,All,"Pride Aloma County, Aundh, , Pune, Maharashtra",9,South-East,Vitrified,Yes,...,0,0,1.0,0.0,0.0,Maintenance 1/ (/ month,1.0,100000.0,1.0,33000.0
5360,2.0,2.0,850.0,Furnished,All,"Swapan Lok Society, Koregaon park, , Pune, Mah...",4,North,Granite,Yes,...,0,0,1.0,0.0,0.0,0,40000.0,120000.0,0.0,40000.0

In [41]:
d.fillna(d['floor_number'].mean())

,bedroom,bathrooms,area,furnishing,avalable_for,address,floor_number,facing,floor_type,gate_community,...,pooja_room,study_room,others,servant_room,store_room,maintenance_amt,brok_amt,deposit_amt,mnt_amt,rent
0,3.081701,2.000000,0.0,Semifurnished,All,"Bella Casa Baner, Baner, , Pune, Maharashtra",1,No Direction,Not provided,No,...,0,0,0.0,0.0,0.0,0,0.0,0.0,0.0,18500.0
1,2.000000,2.000000,1050.0,Semifurnished,All,"Paranjape Blue Ridge, Hinjewadi, , Pune, Mahar...",2,West,Not provided,Yes,...,0,0,0.0,0.0,0.0,0,0.0,63000.0,0.0,21000.0
2,2.000000,3.081701,900.0,Semifurnished,All,"Simplicity Apartments, Handewadi, , Pune, Maha...",6,No Direction,Not provided,Yes,...,0,0,0.0,0.0,0.0,0,0.0,25000.0,0.0,12000.0
3,3.000000,3.000000,1100.0,Furnished,Family Only,"GK Dwarka Queens Park, Rahatani, , Pune, Mahar...",1,East,Others,Yes,...,0,0,0.0,0.0,0.0,0,24000.0,3.0,0.0,24000.0
4,1.000000,1.000000,605.0,Semifurnished,Family Only,"Anandtara Sayajiraje Avenue, Sasane Colony, , ...",4,East,Vitrified,Yes,...,0,0,1.0,0.0,0.0,0,0.0,3.0,0.0,13500.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5356,2.000000,2.000000,0.0,Unfurnished,All,"Kesar Imperial Blue, Dighi, , Pune, Maharashtra",2,East,Marble,Yes,...,0,0,0.0,0.0,0.0,0,0.0,30000.0,0.0,14000.0
5357,1.000000,1.000000,0.0,Unfurnished,Bachelors (Men Only),"Karve Nagar, , Pune, Maharashtra",0,No Direction,Not provided,No,...,0,0,0.0,0.0,0.0,0,0.0,20000.0,0.0,10000.0
5358,3.000000,3.000000,1300.0,Semifurnished,All,"Kolte Patil IVY Estate, Wagholi, , Pune, Mahar...",5,North-West,Marble,Yes,...,0,0,0.0,0.0,1.0,0,16700.0,45000.0,0.0,16700.0
5359,3.000000,3.000000,1450.0,Unfurnished,All,"Pride Aloma County, Aundh, , Pune, Maharashtra",9,South-East,Vitrified,Yes,...,0,0,1.0,0.0,0.0,Maintenance 1/ (/ month,1.0,100000.0,1.0,33000.0
5360,2.000000,2.000000,850.0,Furnished,All,"Swapan Lok Society, Koregaon park, , Pune, Mah...",4,North,Granite,Yes,...,0,0,1.0,0.0,0.0,0,40000.0,120000.0,0.0,40000.0

In [42]:
d.bfill()

,bedroom,bathrooms,area,furnishing,avalable_for,address,floor_number,facing,floor_type,gate_community,...,pooja_room,study_room,others,servant_room,store_room,maintenance_amt,brok_amt,deposit_amt,mnt_amt,rent
0,2.0,2.0,0.0,Semifurnished,All,"Bella Casa Baner, Baner, , Pune, Maharashtra",1,No Direction,Not provided,No,...,0,0,0.0,0.0,0.0,0,0.0,0.0,0.0,18500.0
1,2.0,2.0,1050.0,Semifurnished,All,"Paranjape Blue Ridge, Hinjewadi, , Pune, Mahar...",2,West,Not provided,Yes,...,0,0,0.0,0.0,0.0,0,0.0,63000.0,0.0,21000.0
2,2.0,3.0,900.0,Semifurnished,All,"Simplicity Apartments, Handewadi, , Pune, Maha...",6,No Direction,Not provided,Yes,...,0,0,0.0,0.0,0.0,0,0.0,25000.0,0.0,12000.0
3,3.0,3.0,1100.0,Furnished,Family Only,"GK Dwarka Queens Park, Rahatani, , Pune, Mahar...",1,East,Others,Yes,...,0,0,0.0,0.0,0.0,0,24000.0,3.0,0.0,24000.0
4,1.0,1.0,605.0,Semifurnished,Family Only,"Anandtara Sayajiraje Avenue, Sasane Colony, , ...",4,East,Vitrified,Yes,...,0,0,1.0,0.0,0.0,0,0.0,3.0,0.0,13500.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5356,2.0,2.0,0.0,Unfurnished,All,"Kesar Imperial Blue, Dighi, , Pune, Maharashtra",2,East,Marble,Yes,...,0,0,0.0,0.0,0.0,0,0.0,30000.0,0.0,14000.0
5357,1.0,1.0,0.0,Unfurnished,Bachelors (Men Only),"Karve Nagar, , Pune, Maharashtra",0,No Direction,Not provided,No,...,0,0,0.0,0.0,0.0,0,0.0,20000.0,0.0,10000.0
5358,3.0,3.0,1300.0,Semifurnished,All,"Kolte Patil IVY Estate, Wagholi, , Pune, Mahar...",5,North-West,Marble,Yes,...,0,0,0.0,0.0,1.0,0,16700.0,45000.0,0.0,16700.0
5359,3.0,3.0,1450.0,Unfurnished,All,"Pride Aloma County, Aundh, , Pune, Maharashtra",9,South-East,Vitrified,Yes,...,0,0,1.0,0.0,0.0,Maintenance 1/ (/ month,1.0,100000.0,1.0,33000.0
5360,2.0,2.0,850.0,Furnished,All,"Swapan Lok Society, Koregaon park, , Pune, Mah...",4,North,Granite,Yes,...,0,0,1.0,0.0,0.0,0,40000.0,120000.0,0.0,40000.0

In [43]:
d['last']=d['floor_number']*2
d

,bedroom,bathrooms,area,furnishing,avalable_for,address,floor_number,facing,floor_type,gate_community,...,study_room,others,servant_room,store_room,maintenance_amt,brok_amt,deposit_amt,mnt_amt,rent,last
0,NaN,2.0,0.0,Semifurnished,All,"Bella Casa Baner, Baner, , Pune, Maharashtra",1,No Direction,Not provided,No,...,0,0.0,0.0,0.0,0,0.0,0.0,0.0,18500.0,2
1,2.0,2.0,1050.0,Semifurnished,All,"Paranjape Blue Ridge, Hinjewadi, , Pune, Mahar...",2,West,Not provided,Yes,...,0,0.0,0.0,0.0,0,0.0,63000.0,0.0,21000.0,4
2,2.0,NaN,900.0,Semifurnished,All,"Simplicity Apartments, Handewadi, , Pune, Maha...",6,No Direction,Not provided,Yes,...,0,0.0,0.0,0.0,0,0.0,25000.0,0.0,12000.0,12
3,3.0,3.0,1100.0,Furnished,Family Only,"GK Dwarka Queens Park, Rahatani, , Pune, Mahar...",1,East,Others,Yes,...,0,0.0,0.0,0.0,0,24000.0,3.0,0.0,24000.0,2
4,1.0,1.0,605.0,Semifurnished,Family Only,"Anandtara Sayajiraje Avenue, Sasane Colony, , ...",4,East,Vitrified,Yes,...,0,1.0,0.0,0.0,0,0.0,3.0,0.0,13500.0,8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5356,2.0,2.0,0.0,Unfurnished,All,"Kesar Imperial Blue, Dighi, , Pune, Maharashtra",2,East,Marble,Yes,...,0,0.0,0.0,0.0,0,0.0,30000.0,0.0,14000.0,4
5357,1.0,1.0,0.0,Unfurnished,Bachelors (Men Only),"Karve Nagar, , Pune, Maharashtra",0,No Direction,Not provided,No,...,0,0.0,0.0,0.0,0,0.0,20000.0,0.0,10000.0,0
5358,3.0,3.0,1300.0,Semifurnished,All,"Kolte Patil IVY Estate, Wagholi, , Pune, Mahar...",5,North-West,Marble,Yes,...,0,0.0,0.0,1.0,0,16700.0,45000.0,0.0,16700.0,10
5359,3.0,3.0,1450.0,Unfurnished,All,"Pride Aloma County, Aundh, , Pune, Maharashtra",9,South-East,Vitrified,Yes,...,0,1.0,0.0,0.0,Maintenance 1/ (/ month,1.0,100000.0,1.0,33000.0,18
5360,2.0,2.0,850.0,Furnished,All,"Swapan Lok Society, Koregaon park, , Pune, Mah...",4,North,Granite,Yes,...,0,1.0,0.0,0.0,0,40000.0,120000.0,0.0,40000.0,8

### Explanation of the Function and `.apply()`

1.  **`def fx(v):`**: This defines a custom function named `fx` that takes one input value `v`.
2.  **`return v * v`**: Inside the function, it calculates the square of the input and returns it. This is the logic we want to apply to our data.
3.  **`d['floor_number'].apply(fx)`**: This is the pandas way of looping. It takes every single value in the `floor_number` column and passes it into your `fx` function one by one.
4.  **`d['last+1'] = ...`**: This takes the resulting list of squared values and saves them into a brand new column named `last+1` in your DataFrame `d`.

In [44]:
def fx(v):
    return v * v

# Apply the function to create a new column
d['last+1'] = d['floor_number'].apply(fx)
d.head()

,bedroom,bathrooms,area,furnishing,avalable_for,address,floor_number,facing,floor_type,gate_community,...,others,servant_room,store_room,maintenance_amt,brok_amt,deposit_amt,mnt_amt,rent,last,last+1
0,NaN,2.0,0.0,Semifurnished,All,"Bella Casa Baner, Baner, , Pune, Maharashtra",1,No Direction,Not provided,No,...,0.0,0.0,0.0,0,0.0,0.0,0.0,18500.0,2,1
1,2.0,2.0,1050.0,Semifurnished,All,"Paranjape Blue Ridge, Hinjewadi, , Pune, Mahar...",2,West,Not provided,Yes,...,0.0,0.0,0.0,0,0.0,63000.0,0.0,21000.0,4,4
2,2.0,NaN,900.0,Semifurnished,All,"Simplicity Apartments, Handewadi, , Pune, Maha...",6,No Direction,Not provided,Yes,...,0.0,0.0,0.0,0,0.0,25000.0,0.0,12000.0,12,36
3,3.0,3.0,1100.0,Furnished,Family Only,"GK Dwarka Queens Park, Rahatani, , Pune, Mahar...",1,East,Others,Yes,...,0.0,0.0,0.0,0,24000.0,3.0,0.0,24000.0,2,1
4,1.0,1.0,605.0,Semifurnished,Family Only,"Anandtara Sayajiraje Avenue, Sasane Colony, , ...",4,East,Vitrified,Yes,...,1.0,0.0,0.0,0,0.0,3.0,0.0,13500.0,8,16

In [45]:
# Filter the DataFrame for rows where 'bedroom' is null
d[d['bedroom'].isnull()]

,bedroom,bathrooms,area,furnishing,avalable_for,address,floor_number,facing,floor_type,gate_community,...,others,servant_room,store_room,maintenance_amt,brok_amt,deposit_amt,mnt_amt,rent,last,last+1
0,NaN,2.0,0.0,Semifurnished,All,"Bella Casa Baner, Baner, , Pune, Maharashtra",1,No Direction,Not provided,No,...,0.0,0.0,0.0,0,0.0,0.0,0.0,18500.0,2,1

In [46]:
# Drop columns with at least one missing value
d.dropna(axis=1)

,area,furnishing,address,floor_number,facing,floor_type,gate_community,noticeDur,powerbackup,propertyage,pooja_room,study_room,mnt_amt,rent,last,last+1
0,0.0,Semifurnished,"Bella Casa Baner, Baner, , Pune, Maharashtra",1,No Direction,Not provided,No,0,0,1 to 5 Year Old,0,0,0.0,18500.0,2,1
1,1050.0,Semifurnished,"Paranjape Blue Ridge, Hinjewadi, , Pune, Mahar...",2,West,Not provided,Yes,1,1,0 to 1 Year Old,0,0,0.0,21000.0,4,4
2,900.0,Semifurnished,"Simplicity Apartments, Handewadi, , Pune, Maha...",6,No Direction,Not provided,Yes,1,2,5 to 10 Year Old,0,0,0.0,12000.0,12,36
3,1100.0,Furnished,"GK Dwarka Queens Park, Rahatani, , Pune, Mahar...",1,East,Others,Yes,1,1,5 to 10 Year Old,0,0,0.0,24000.0,2,1
4,605.0,Semifurnished,"Anandtara Sayajiraje Avenue, Sasane Colony, , ...",4,East,Vitrified,Yes,1,1,5 to 10 Year Old,0,0,0.0,13500.0,8,16
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5356,0.0,Unfurnished,"Kesar Imperial Blue, Dighi, , Pune, Maharashtra",2,East,Marble,Yes,1,0,0 to 1 Year Old,0,0,0.0,14000.0,4,4
5357,0.0,Unfurnished,"Karve Nagar, , Pune, Maharashtra",0,No Direction,Not provided,No,0,0,5 to 10 Year Old,0,0,0.0,10000.0,0,0
5358,1300.0,Semifurnished,"Kolte Patil IVY Estate, Wagholi, , Pune, Mahar...",5,North-West,Marble,Yes,1,2,0 to 1 Year Old,0,0,0.0,16700.0,10,25
5359,1450.0,Unfurnished,"Pride Aloma County, Aundh, , Pune, Maharashtra",9,South-East,Vitrified,Yes,1,2,5 to 10 Year Old,0,0,1.0,33000.0,18,81
5360,850.0,Furnished,"Swapan Lok Society, Koregaon park, , Pune, Mah...",4,North,Granite,Yes,1,2,10+ Year Old,0,0,0.0,40000.0,8,16