<a href="https://colab.research.google.com/github/manojmulammagari/data-analysis-python-practice/blob/main/Pandas_02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [67]:
import pandas as pd

In [68]:
data={
    'Name':['John','Jane','Bob'],
    'Subject':['Math','Science','History'],
    'Marks':[85,91,78],
    'Passed':[True,True,False]
}
df=pd.DataFrame(data)
df

   Name  Subject  Marks  Passed
0  John     Math     85    True
1  Jane  Science     91    True
2   Bob  History     78   False

In [69]:
df.index

RangeIndex(start=0, stop=3, step=1)

In [70]:
df.axes

[RangeIndex(start=0, stop=3, step=1),
 Index(['Name', 'Subject', 'Marks', 'Passed'], dtype='object')]

In [71]:
df.dtypes

Name       object
Subject    object
Marks       int64
Passed       bool
dtype: object

In [72]:
df.columns,df.values

(Index(['Name', 'Subject', 'Marks', 'Passed'], dtype='object'),
 array([['John', 'Math', 85, True],
        ['Jane', 'Science', 91, True],
        ['Bob', 'History', 78, False]], dtype=object))

In [73]:
# loading datasets
df = pd.read_csv('/content/education_vs_income_econometrics_samples.csv')
df.head(7)
# df = pd.read_excel('your_dataset.xlsx')

   obs sample  x_education_years  y_income_thousands_usd
0    1      A                  8                    18.5
1    2      A                  9                    20.2
2    3      A                 10                    22.8
3    4      A                 11                    24.5
4    5      A                 12                    27.3
5    6      A                 13                    29.8
6    7      A                 14                    33.2

In [74]:
df.head()

   obs sample  x_education_years  y_income_thousands_usd
0    1      A                  8                    18.5
1    2      A                  9                    20.2
2    3      A                 10                    22.8
3    4      A                 11                    24.5
4    5      A                 12                    27.3

In [75]:
df.tail()

    obs sample  x_education_years  y_income_thousands_usd
15    6      B                 13                    31.2
16    7      B                 14                    34.7
17    8      B                 15                    38.0
18    9      B                 16                    44.5
19   10      B                 18                    55.1

In [76]:
df.shape

(20, 4)

In [77]:
df.sample(4)

    obs sample  x_education_years  y_income_thousands_usd
13    4      B                 11                    25.8
19   10      B                 18                    55.1
0     1      A                  8                    18.5
15    6      B                 13                    31.2

In [78]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 4 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   obs                     20 non-null     int64
 1   sample                  20 non-null     object
 2   x_education_years       20 non-null     int64
 3   y_income_thousands_usd  20 non-null     float64
dtypes: float64(1), int64(2), object(1)
memory usage: 772.0+ bytes

In [79]:
df.describe()

             obs  x_education_years  y_income_thousands_usd
count  20.000000          20.000000               20.000000
mean    5.500000          12.600000               31.295000
std     2.946898           3.118704               10.783832
min     1.000000           8.000000               17.900000
25%     3.000000          10.000000               23.325000
50%     5.500000          12.500000               28.550000
75%     8.000000          15.000000               36.875000
max    10.000000          18.000000               55.100000

In [80]:
data=df.set_index('sample')
print(data)

        obs  x_education_years  y_income_thousands_usd
sample
A         1                  8                    18.5
A         2                  9                    20.2
A         3                 10                    22.8
A         4                 11                    24.5
A         5                 12                    27.3
A         6                 13                    29.8
A         7                 14                    33.2
A         8                 15                    36.5
A         9                 16                    42.1
A        10                 18                    52.4
B         1                  8                    17.9
B         2                  9                    21.0
B         3                 10                    23.5
B         4                 11                    25.8
B         5                 12                    26.9
B         6                 13                    31.2
B         7                 14                    34.7
B         8                 15                    38.0
B         9                 16                    44.5
B        10                 18                    55.1

In [81]:
data.loc['B',['obs',"x_education_years"]]

        obs  x_education_years
sample
B         1                  8
B         2                  9
B         3                 10
B         4                 11
B         5                 12
B         6                 13
B         7                 14
B         8                 15
B         9                 16
B        10                 18

### Renaming Columns and Converting to Datetime

To rename specific columns, you can use a dictionary with the mapping `{old_name: new_name}`.

To convert a string or numeric column to actual datetime objects, use `pd.to_datetime()`.

In [82]:
# 1. Renaming columns
df = df.rename(columns={'sample': 'grade', 'y_income_thousands_usd': 'marks'})

# 2. Converting to datetime
# Note: If you had a 'date' column string like '2023-01-01'
# df['date_column'] = pd.to_datetime(df['date_column'])

display(df.head())

   obs grade  x_education_years  marks
0    1     A                  8   18.5
1    2     A                  9   20.2
2    3     A                 10   22.8
3    4     A                 11   24.5
4    5     A                 12   27.3

In [83]:
df

    obs grade  x_education_years  marks
0     1     A                  8   18.5
1     2     A                  9   20.2
2     3     A                 10   22.8
3     4     A                 11   24.5
4     5     A                 12   27.3
5     6     A                 13   29.8
6     7     A                 14   33.2
7     8     A                 15   36.5
8     9     A                 16   42.1
9    10     A                 18   52.4
10    1     B                  8   17.9
11    2     B                  9   21.0
12    3     B                 10   23.5
13    4     B                 11   25.8
14    5     B                 12   26.9
15    6     B                 13   31.2
16    7     B                 14   34.7
17    8     B                 15   38.0
18    9     B                 16   44.5
19   10     B                 18   55.1

In [84]:
import numpy as np

# Define the possible grades
grades_list = ['A', 'B', 'C', 'D', 'E']

# Assign a random grade to each row
df['grade'] = np.random.choice(grades_list, size=len(df))

display(df.head(10))

   obs grade  x_education_years  marks
0    1     C                  8   18.5
1    2     D                  9   20.2
2    3     C                 10   22.8
3    4     B                 11   24.5
4    5     E                 12   27.3
5    6     D                 13   29.8
6    7     E                 14   33.2
7    8     D                 15   36.5
8    9     C                 16   42.1
9   10     C                 18   52.4

In [85]:
# Show the 'axes' of the dataframe
# This returns a list: [Row Index, Column Names]
print("The axes of the DataFrame are:")
display(df.axes)

The axes of the DataFrame are:

[RangeIndex(start=0, stop=20, step=1),
 Index(['obs', 'grade', 'x_education_years', 'marks'], dtype='object')]

In [86]:
import pandas as pd
import numpy as np

# Create a small example with a NaN
demo_df = pd.DataFrame({
    'A': [10, 20, np.nan],
    'B': [5, 5, 5]
})

print("1. Original DataFrame:")
display(demo_df)

print("\n2. Sum with axis=0 (Calculates sum for each COLUMN):")
# This collapses rows, giving a result for each column
display(demo_df.sum(axis=0))

print("\n3. Sum with axis=1 (Calculates sum for each ROW):")
# This collapses columns, giving a result for each row
display(demo_df.sum(axis=1))

print("\nNote: If you use axis=0 on the main 'df', the 'grade' column (strings) might cause issues in some versions or return NaN/empty results for math.")

1. Original DataFrame:

      A  B
0  10.0  5
1  20.0  5
2   NaN  5

2. Sum with axis=0 (Calculates sum for each COLUMN):

A    30.0
B    15.0
dtype: float64

3. Sum with axis=1 (Calculates sum for each ROW):

0    15.0
1    25.0
2     5.0
dtype: float64

Note: If you use axis=0 on the main 'df', the 'grade' column (strings) might cause issues in some versions or return NaN/empty results for math.

In [87]:
# Example of using axis=0
# We will calculate the average (mean) for each numeric column

# We select only the numeric columns first to avoid errors with strings
numeric_df = df[['x_education_years', 'marks']]

print("Average values for each COLUMN (using axis=0):")
column_averages = numeric_df.mean(axis=0)
display(column_averages)

print("\nMaximum values for each COLUMN (using axis=0):")
column_max = numeric_df.max(axis=0)
display(column_max)

Average values for each COLUMN (using axis=0):

x_education_years    12.600
marks                31.295
dtype: float64

Maximum values for each COLUMN (using axis=0):

x_education_years    18.0
marks                55.1
dtype: float64

In [96]:
print(f"Type of df['marks']: {type(df['marks'])}")
print(f"Type of df: {type(df)}")

# This works because it's a Series (1D)
test_series = df['marks'].apply(lambda x: x * 2)
print("\nSeries apply worked without axis.")

try:
    # This would fail because the DataFrame (2D) doesn't know which direction to go
    df.apply(lambda x: x * 2)
except Exception as e:
    print(f"\nDataFrame apply failed without axis: {e}")

Type of df['marks']: <class 'pandas.core.series.Series'>
Type of df: <class 'pandas.core.frame.DataFrame'>

Series apply worked without axis.

In [89]:
def pass_fail(score):
  if score>=20:
    return "Pass"
  else:
    return "Fail"

df["Results"]=df["marks"].apply(pass_fail)
df.head()

   obs grade  x_education_years  marks Results
0    1     C                  8   18.5    Fail
1    2     D                  9   20.2    Pass
2    3     C                 10   22.8    Pass
3    4     B                 11   24.5    Pass
4    5     E                 12   27.3    Pass

In [90]:
import random

# 1. We define the list of possible values
grades = ['A', 'B', 'C', 'D', 'E']

# 2. We use .apply() with a lambda function
# - 'lambda row:' is a small function that runs for every row
# - 'random.choice(grades)' picks one random letter from our list
# - 'axis=1' tells pandas to move through the table row by row
df['grade'] = df.apply(lambda x: random.choice(grades), axis=1)

# 3. Show the results
display(df.head())

   obs grade  x_education_years  marks Results
0    1     D                  8   18.5    Fail
1    2     A                  9   20.2    Pass
2    3     C                 10   22.8    Pass
3    4     B                 11   24.5    Pass
4    5     D                 12   27.3    Pass

### Using .apply(axis=1) across multiple columns

When we use `axis=1`, the variable `row` in our function represents a single horizontal record from the table.

In [91]:
# Example 1: Using a Lambda to combine columns
# Let's create a 'Status' string using both 'grade' and 'Results' columns
# df['Summary'] = df.apply(lambda r: f"Grade {r['grade']} was a {r['Results']}", axis=1)

# Example 2: Using a Defined Function for complex multi-column logic
def calculate_bonus(r):
    # Logic using two different columns
    if r['marks'] > 40 and r['x_education_years'] > 15:
        return "High Performance"
    else:
        return "Standard"

df['Performance_Tag'] = df.apply(calculate_bonus, axis=1)

display(df.head())

   obs grade  x_education_years  marks Results Performance_Tag
0    1     D                  8   18.5    Fail        Standard
1    2     A                  9   20.2    Pass        Standard
2    3     C                 10   22.8    Pass        Standard
3    4     B                 11   24.5    Pass        Standard
4    5     D                 12   27.3    Pass        Standard

In [92]:
grade_mapping={
    'A':"Excellent",
    'B':"Good",
    'C':"Average",
    'D':"Below Average",
    'E':"Fail/Need to practice more"
}

df["grade_description"]=df["grade"].map(grade_mapping)
df[["obs","grade",'Results','grade_description']].head(7)

   obs grade Results grade_description
0    1     D    Fail     Below Average
1    2     A    Pass         Excellent
2    3     C    Pass           Average
3    4     B    Pass              Good
4    5     D    Pass     Below Average
5    6     C    Pass           Average
6    7     D    Pass     Below Average

In [93]:
df

,obs,grade,x_education_years,marks,Results,Performance_Tag,grade_description
0,1,D,8,18.5,Fail,Standard,Below Average
1,2,A,9,20.2,Pass,Standard,Excellent
2,3,C,10,22.8,Pass,Standard,Average
3,4,B,11,24.5,Pass,Standard,Good
4,5,D,12,27.3,Pass,Standard,Below Average
5,6,C,13,29.8,Pass,Standard,Average
6,7,D,14,33.2,Pass,Standard,Below Average
7,8,B,15,36.5,Pass,Standard,Good
8,9,A,16,42.1,Pass,High Performance,Excellent
9,10,C,18,52.4,Pass,High Performance,Average
10,1,A,8,17.9,Fail,Standard,Excellent
11,2,D,9,21.0,Pass,Standard,Below Average
12,3,E,10,23.5,Pass,Standard,Fail/Need to practice more
13,4,E,11,25.8,Pass,Standard,Fail/Need to practice more
14,5,A,12,26.9,Pass,Standard,Excellent
15,6,A,13,31.2,Pass,Standard,Excellent
16,7,B,14,34.7,Pass,Standard,Good
17,8,D,15,38.0,Pass,Standard,Below Average
18,9,E,16,44.5,Pass,High Performance,Fail/Need to practice more
19,10,C,18,55.1,Pass,High Performance,Average

In [97]:
a=df.sort_values(by='marks',ascending=True)
a

,obs,grade,x_education_years,marks,Results,Performance_Tag,grade_description
10,1,A,8,17.9,Fail,Standard,Excellent
0,1,D,8,18.5,Fail,Standard,Below Average
1,2,A,9,20.2,Pass,Standard,Excellent
11,2,D,9,21.0,Pass,Standard,Below Average
2,3,C,10,22.8,Pass,Standard,Average
12,3,E,10,23.5,Pass,Standard,Fail/Need to practice more
3,4,B,11,24.5,Pass,Standard,Good
13,4,E,11,25.8,Pass,Standard,Fail/Need to practice more
14,5,A,12,26.9,Pass,Standard,Excellent
4,5,D,12,27.3,Pass,Standard,Below Average
5,6,C,13,29.8,Pass,Standard,Average
15,6,A,13,31.2,Pass,Standard,Excellent
6,7,D,14,33.2,Pass,Standard,Below Average
16,7,B,14,34.7,Pass,Standard,Good
7,8,B,15,36.5,Pass,Standard,Good
17,8,D,15,38.0,Pass,Standard,Below Average
8,9,A,16,42.1,Pass,High Performance,Excellent
18,9,E,16,44.5,Pass,High Performance,Fail/Need to practice more
9,10,C,18,52.4,Pass,High Performance,Average
19,10,C,18,55.1,Pass,High Performance,Average

In [95]:
a.sort_index()

,obs,grade,x_education_years,marks,Results,Performance_Tag,grade_description
0,1,D,8,18.5,Fail,Standard,Below Average
1,2,A,9,20.2,Pass,Standard,Excellent
2,3,C,10,22.8,Pass,Standard,Average
3,4,B,11,24.5,Pass,Standard,Good
4,5,D,12,27.3,Pass,Standard,Below Average
5,6,C,13,29.8,Pass,Standard,Average
6,7,D,14,33.2,Pass,Standard,Below Average
7,8,B,15,36.5,Pass,Standard,Good
8,9,A,16,42.1,Pass,High Performance,Excellent
9,10,C,18,52.4,Pass,High Performance,Average
10,1,A,8,17.9,Fail,Standard,Excellent
11,2,D,9,21.0,Pass,Standard,Below Average
12,3,E,10,23.5,Pass,Standard,Fail/Need to practice more
13,4,E,11,25.8,Pass,Standard,Fail/Need to practice more
14,5,A,12,26.9,Pass,Standard,Excellent
15,6,A,13,31.2,Pass,Standard,Excellent
16,7,B,14,34.7,Pass,Standard,Good
17,8,D,15,38.0,Pass,Standard,Below Average
18,9,E,16,44.5,Pass,High Performance,Fail/Need to practice more
19,10,C,18,55.1,Pass,High Performance,Average